### ISSUE TITLE
Create the Homepage

### ISSUE THREAD

**Issue by aashish-ak** [KamandPrompt/CodeManiacs#1]
You need to create the homepage with design similar to [codechef](www.codechef.com), create the best possible design using expressJS ejs middleware. Add files as you please

**Comment by Vishal1541** [comment]
@dipanshu231099 good luck. Start working on it :+1:

**Comment by Vishal1541** [comment]
@dipanshu231099 How much progress?

**Comment by dipanshu231099** [comment]
I am still in the process of making

**Comment by dipanshu231099** [comment]
moreover my forked repository is not updating with the changes in the main directory how do we do it

**Comment by vsvipul** [comment]
> updating with the changes in the main directory how do

https://help.github.com/articles/syncing-a-fork/
https://zulip.readthedocs.io/en/latest/git/using.html?fbclid=IwAR1_IweZm408KDmLrPZ8VwhuryX8PlySs_yOYcgmegh0RkNn1K0HVcB7kkY#keep-your-fork-up-to-date
