### ISSUE TITLE
Connect Homepage with Login/Signup page.

### ISSUE THREAD

**Issue by aashish-ak** [KamandPrompt/CodeManiacs#13]
The homepage should provide a login/signup button (if not logged in) and a dashboard/profile button if logged in. The login status should be checked in with the Google firebase API, which is already implemented.

**Comment by aashish-ak** [comment]
Yes, Firebase API provides a method for that.

**Comment by aashish-ak** [comment]
@dipanshu231099  Any progress on this one?

**Comment by dipanshu231099** [comment]
connect kaise krna hai iske liye kuchh bhi smjh nhi aa rha

**Comment by aashish-ak** [comment]
Page bngaya pura?

**Comment by dipanshu231099** [comment]
signup login page to bnaa hua hai na??

**Comment by dipanshu231099** [comment]
https://stackoverflow.com/questions/37873608/how-do-i-detect-if-a-user-is-already-logged-in-firebase
yeh hai method kya?

**Comment by RikaShah** [comment]
I have already added this firebase check status, in the login app of react-dom, so you have to add cdn files, alongwith script tags in home page for compatibility with react-pack
