### ISSUE TITLE
Testcase File

### ISSUE THREAD

**Issue by phamminhtuan1999** [KamandPrompt/CodeManiacs#135]
Hi. What kind of Testcase file? .Txt or .Json or .Js. How can I structure that? Can you give me an example of Testcase file, please. Thank for your support

**Comment by pranshukharkwal** [comment]
Hi @phamminhtuan1999 
Testcase files are just txt files in this format : 
```
input


output
```

input and output texts separated by two lines.

**Comment by pranshukharkwal** [comment]
@dheeraj135 You may close this issue as well
