### ISSUE TITLE
Add dummy codes for different languages in submit page

### ISSUE THREAD

**Issue by pranshukharkwal** [KamandPrompt/CodeManiacs#142]
This issue has already been fixed for the /ide route : http://localhost:3000/ide
But still exists in http://localhost:3000/submit/:qNo

Check this PR for the fix for the ide route : #138

**Comment by shrirangpdeshmukh** [comment]
Can I work on this issue?

**Comment by pranshukharkwal** [comment]
@shrirangpdeshmukh 
Yes go ahead with this one. Also I would not suggest you to pick multiple issues at once. 
Pick this one, and after doing it, you can move to the other one.
