### ISSUE TITLE
Add "Copy" button in problem page to copy sample input and sample output to the clipboard

### ISSUE THREAD

**Issue by pranshukharkwal** [KamandPrompt/CodeManiacs#143]
In the route : http://localhost:3000/problem/:qNo
Add a copy button with the sample input and the sample output sections, add a copy button, which would copy the corresponding text to the clipboard.

**Comment by Piyush3436** [comment]
@pranshukharkwal I'll take this up. Please assign the issue to me.

**Comment by pranshukharkwal** [comment]
@Piyush3436 sure
