### ISSUE TITLE
Make delete button smaller on admin page

### ISSUE THREAD

**Issue by Signior-X** [KamandPrompt/CodeManiacs#145]

**Comment by Signior-X** [comment]
Like see the admin page
![image](https://user-images.githubusercontent.com/56730716/101275233-1fb7e900-37ca-11eb-865a-eb49125f0e3d.png)

Make the delete button smaller, you can change the class searching `bootstrap buttons` on google.

**Comment by Piyush3436** [comment]
I'll work on this.

**Comment by ineffable23** [comment]
I'm interested

**Comment by Signior-X** [comment]
@ineffable23 this issue was already being fixed by @Piyush3436 
You can look at other issues for the time being.
