### ISSUE TITLE
[BUG] Link to problem in an individual problem submission page points to a wrong url

### ISSUE THREAD

**Issue by pranshukharkwal** [KamandPrompt/CodeManiacs#156]
![Screenshot from 2020-12-09 19-47-21](https://user-images.githubusercontent.com/21126219/101641155-6bcb8d80-3a57-11eb-8840-7a7a300a2f2d.png)
http://localhost:3000/user/submission/28
Check this route : /user/submission/:submissionId , example : /user/submission/5
Here in the problem column, the link points to the submission with submission id, but instead it should point to the problem with that problem id.

**Comment by Gautam-Arora24** [comment]
@kpbot claim

**Comment by Ayushgup85** [comment]
Can i work on this issue?

**Comment by pranshukharkwal** [comment]
@Gautam-Arora24 Yes you can work on this issue. 
@Ayushgup85 you can pick other issues.

**Comment by Gautam-Arora24** [comment]
Is **qId** the id for a particular question?

**Comment by pranshukharkwal** [comment]
@Gautam-Arora24 yes

**Comment by Gautam-Arora24** [comment]
@pranshukharkwal Kindly provide me the dummy details of any problem so that I can check and submit any solution for that.

**Comment by pranshukharkwal** [comment]
@Gautam-Arora24 you can enter any random text for dummy details, or you can also pick any problem from sites like codeforces, codechef etc.
