### ISSUE TITLE
Disappearing of images after 1.5seconds.

### ISSUE THREAD

**Issue by Creatoon** [KamandPrompt/CodeManiacs#169]
Whenever a new image gets loaded it stays for 1.5s and gets disappeared.

To Reproduce,
1) Visit the About section.
2) Click the forward and backward buttons to see the disappearing defect.

![CodemanBugFix](https://user-images.githubusercontent.com/65965202/101996484-df3ffa00-3cf8-11eb-998a-61d909cf123f.PNG)

After few seconds.

![codemanBug](https://user-images.githubusercontent.com/65965202/101996497-f979d800-3cf8-11eb-80f5-8b49cb05ee71.PNG)

**Comment by Signior-X** [comment]
Nice issue created! Well done @Creatoon 
Reviewing your PR.. stay tuned!
