### ISSUE TITLE
Create a webpage to display problems.

### ISSUE THREAD

**Issue by Vishal1541** [KamandPrompt/CodeManiacs#18]
Add a webpage to show all the problems. It should have a table with **Prob ID**, **Prob Name** and **Tags**. Also, add a link to the problem set on the homepage. For reference look at the codeforces problem set: 
![prob](https://user-images.githubusercontent.com/20883811/50393057-92646100-0779-11e9-866f-7d78d9e914ef.png)

**Comment by Milind712000** [comment]
I'll do this

**Comment by Vishal1541** [comment]
@Milind712000 Good luck. Start with it :+1:
