### ISSUE TITLE
Create a page to submit the code

### ISSUE THREAD

**Issue by Vishal1541** [KamandPrompt/CodeManiacs#22]
Create a page where the user can paste the code and submit it. As of now create this as an independent page. Afterward, this page will be linked to the specific problem by passing the problem code through the URL. It should have a _code editor interface_, _dropdown_ to select the Lang/ Compiler and a _submit button_ to submit the code finally. For reference, you can look at the CodeChef or Codeforces submit page.

![submit_page](https://user-images.githubusercontent.com/20883811/50733431-51c20a00-11b3-11e9-994f-e393454f7ee1.png)
![submit_page2](https://user-images.githubusercontent.com/20883811/50733432-525aa080-11b3-11e9-924b-c36f8775748e.png)

**Comment by Vishal1541** [comment]
Open `http://localhost:3000/submitprob?<questionID>` to open the submit page for that problem.
![submit_prob](https://user-images.githubusercontent.com/20883811/50823439-0564fe80-135a-11e9-986f-07ac087345d6.png)

**Comment by aashish-ak** [comment]
Good job @Vishal1541 , this looks nice, but make sure one thing that if your code in it, you're able to extract the whole code as in the php version of codemaniacs, when i integrated the editor with the app and when i extracted code from the editor to send it to the judge API, the code wasn't as a single text but an array of length no. of lines, which gave me some problem, so make sure this one doesn't do that rest everything is good.

**Comment by Vishal1541** [comment]
@aashish-ak I used [Ace code editor](https://ace.c9.io/). It has a function to extract the whole code at once.
