### ISSUE TITLE
Connect the app to Judge0 API.

### ISSUE THREAD

**Issue by aashish-ak** [KamandPrompt/CodeManiacs#23]
The code submitted by user should be added to a JSON object along with details metioned [here](http://sntc.iitmandi.ac.in:3000) , and should be sent to the API, so design an interface to do this task, the JS scripts, should be able to extract data regarding the question from firebase and should be able to handle the API response as well. It is a [Judge0 API](https://github.com/judge0/api) which is currently hosted on IIT Mandi SNTC Server, the authentication token will be provided to you once you start working on this issue.

**Comment by Milind712000** [comment]
I'll try it

**Comment by aashish-ak** [comment]
Work on it, we'll help you in the process.
