### ISSUE TITLE
Create a platform for editing problems and test cases

### ISSUE THREAD

**Issue by Vishal1541** [KamandPrompt/CodeManiacs#26]
The admin login system can be implemented and integrated later. As of now, the problem description can be submitted through http://localhost:3000/question/submit. We need a platform for modifying the already created problems (editing prob desc, uploading/ modifying the test cases).
Create a page http://localhost:3000/admin to list all the existing problems. Eg. Codechef panel:
![cc_admin](https://user-images.githubusercontent.com/20883811/51457718-689e5a00-1d78-11e9-98ad-6705fc1c0a04.png)
Clicking on any problem link should open a page http://localhost:3000/admin/edit?<probID> to modify the data. First section should contain all the fields that were there in while submitting the new  question. Eg. Codeforces panel:
![cf_admin](https://user-images.githubusercontent.com/20883811/51457882-1a3d8b00-1d79-11e9-9d2d-bd4989674b1e.png)
Second section for uploading and modifying the test cases. Eg. Hackerearth panel:
![hackerearth_admin](https://user-images.githubusercontent.com/20883811/51457947-638dda80-1d79-11e9-8c36-7aecf16bdf0c.png)

**Comment by Milind712000** [comment]
I feel that a new page displaying a list of questions isn't required as we already have a problemset page
The edit page is almost the submit page and display page combined except:
- it can display testcases (display page won't as normal users shouldn't have access to those)
- it can change values of a question and testcase, given its id
- requires the user to be logged as admin

I can modify the submit page to double as an edit page or I can create a new page(most of the code will be same as the submit page)

**Comment by Vishal1541** [comment]
@Milind712000 we can use the same problem set page with the route /admin , but create a new page for editing the problems/ test cases. Once the admin click on any of the problem, he'll we directed to this edit page. This page has route /admin/edit? . Also, keep the fonts and elements styling small on this edit page.
