### ISSUE TITLE
Create a User Dashboard. 

### ISSUE THREAD

**Issue by aashish-ak** [KamandPrompt/CodeManiacs#3]
Create a user profile page layout. It should **at least** contain the following fields to show the user information: _Name, Username, Email, Total soln submitted, Total AC, Total WA, Total TLE, a link to MySubmission page: http://localhost:3000/user/submissions (#41 )_.
route: http://localhost:3000/user/profile
ejs file: `./views/profile.ejs`

You can look at https://www.codechef.com/users/vishal_nnd0 for reference. Feel free to show your creativity :smiley:

**Comment by rapperdinesh** [comment]
I want to work on this issue

**Comment by aashish-ak** [comment]
This issue has a dependency which is #2 , you need to complete that one first in order to work on this one, also the issues with `good first issue` label are preffered for beginners.

**Comment by aashish-ak** [comment]
@rapperdinesh  Any progress on this issue?

**Comment by rapperdinesh** [comment]
not till now...completing the ranklist issue first

**Comment by Vishal1541** [comment]
Basic layout completed:
![cm_profile](https://user-images.githubusercontent.com/20883811/52291467-6ce18e80-2998-11e9-9091-377e4aa28d54.png)
