### ISSUE TITLE
Create a global ranklist of all the users. 

### ISSUE THREAD

**Issue by aashish-ak** [KamandPrompt/CodeManiacs#4]
A global ranklist should sort the users based on a few parameters like, how much questions he/she has solved, his/her accuracy, no. of submissions in each question. This can only be resolved after creation of a question database as user can only submit after that.

**Comment by rapperdinesh** [comment]
I wish to work on this issue. Please assign. Till the completion of question database,
I can work on algorithm and interface and test it with trial inputs

**Comment by Vishal1541** [comment]
@rapperdinesh good luck. Start with the issue
