### ISSUE TITLE
Implement user authentication using passport js

### ISSUE THREAD

**Issue by Vishal1541** [KamandPrompt/CodeManiacs#40]
Implement user authentication using passport js. Potential files: 

- Signu form: `./views/signup.ejs` 

- Login form: `./views/login.ejs`

- `./config/passport.js`

- `./routes/users.js`

- Schema: `./models/users.js`

- Implement any helper other helper functions in `./controls/functions.js`

**Comment by RikaShah** [comment]
sir, i wish to take effort on this, please let me do it
