### ISSUE TITLE
Edit problems to the database

### ISSUE THREAD

**Issue by Vishal1541** [KamandPrompt/CodeManiacs#42]
Route: http://localhost:3000/admin/edit/:qID
The app is connected to the database: `./config/database.js`. Edit the problems to the database. The schema is in `./models/problems.js` and `./models/testcases.js`.
Basically, you'll have to implement the function: `editQuestion()` in the file `./controls/admin.js`. You can add other helping functions there.

**Comment by dipanshu231099** [comment]
can i do it?

**Comment by dipanshu231099** [comment]
is this assigned to milind?
