### ISSUE TITLE
Display problems in Problem Set

### ISSUE THREAD

**Issue by Vishal1541** [KamandPrompt/CodeManiacs#44]
Currently, the table data is hard-coded. Display all the problems whose `isVisible` is **true** in **descending** order of the **qID**.
URL: http://localhost:3000/problems/all
ejs: `./views/problem_set.ejs`
route: `./routes/index.js`
You can create js file in: `./public/js/problem_set.ejs` if necessary.

**Comment by dipanshu231099** [comment]
on it
