### ISSUE TITLE
Create a Google Firebase database of Problem Statements.

### ISSUE THREAD

**Issue by aashish-ak** [KamandPrompt/CodeManiacs#5]
The database should be hosted on Google firebase and should contain a proper schema of the database, like the problem id, statement, difficulty level, problem setter, the contest it was a part of, no. of people who have solved it, no. of peoople who have tried it etc., One should be able to push questions to the realtime database and fetch at the same time.

**Comment by Vishal1541** [comment]
@Milind712000 good luck. Start working on this issue. Keep discussing related stuff under this thread as db plays a major role.
