### ISSUE TITLE
Add submission details after submitting any problem

### ISSUE THREAD

**Issue by Vishal1541** [KamandPrompt/CodeManiacs#50]
The submission schema should look like:
username: String,
    qID: Number,
    subID: Number,
    code: String,
    language: String,
    verdict: String,
    time: Number,
    memory: Number,
    isVisible: Boolean,
    timeStamp: Date,
    tc: [{ status: String, time: Number, memory: Number }]

The subID will be 1 + total no of submissions till now. URL: http://localhost:3000/submit/:qID

**Comment by vsvipul** [comment]
on it

**Comment by Vishal1541** [comment]
The main function to edit is in `./controls/problems.js`: `submitSolution()`

**Comment by Vishal1541** [comment]
Also, @vsvipul, the first non AC status will be the verdict and hence the time and memory, else the verdict will be "Accepted" and time = max(tc(time)) and memory = max(tc(memory))

**Comment by vsvipul** [comment]
why max and not avg @Vishal1541  ?

**Comment by Vishal1541** [comment]
@vsvipul in case of AC it kinda shows how much worse or good is your solution (by looking at the worst case time and memory taken). The same happens in Codechef and Codeforces.
