### ISSUE TITLE
Add solved property in problems model

### ISSUE THREAD

**Issue by vsvipul** [KamandPrompt/CodeManiacs#52]
Add a property 'solved' to show how many people have solved that particular problem.

**Comment by vsvipul** [comment]
yeah but submissions will generally be very high on such a website .. so don't u think it's better to just store it instead of querying the whole db @Vishal1541  ?

**Comment by Vishal1541** [comment]
@vsvipul I have currently implemented it using query: http://localhost:3000/problems/all (`solved column`) and closing this issue for now. We can discuss it and come up with some better approach, if possible, because we also need to show which users have solved that problem.
