### ISSUE TITLE
Make rankings page header similar to other pages

### ISSUE THREAD

**Issue by vsvipul** [KamandPrompt/CodeManiacs#59]

**Comment by Vishal1541** [comment]
Actually this page instead of modification needs to be replaced with a new one to match with all other pages. All other page tables are similar but this one is odd one out.

**Comment by vsvipul** [comment]
> Actually this page instead of modification needs to be replaced with a new one to match with all other pages. All other page tables are similar but this one is odd one out.

yeah that is what i meant :+1:
