### ISSUE TITLE
Make the footer stick to the bottom.

### ISSUE THREAD

**Issue by Vishal1541** [KamandPrompt/CodeManiacs#65]
Make the footer section stick to the bottom of the webpage.
URL: http://localhost:3000/ http://localhost:3000/user/login http://localhost:3000/user/signup http://localhost:3000/contribution

**Comment by Milind712000** [comment]
also : http://localhost:3000/user/profile

**Comment by Milind712000** [comment]
+ not_found.ejs

**Comment by Milind712000** [comment]
I'll work on this issue

**Comment by Vishal1541** [comment]
@Milind712000 Go ahead!  :+1:
