### ISSUE TITLE
Create a Login/Signup page!

### ISSUE THREAD

**Issue by aashish-ak** [KamandPrompt/CodeManiacs#7]
You need to create a login/signup page and call the functions from the Firebase API that has already been implemented by @vsvipul , the HTML , CSS should be done from scratch, no templates are allowed, the page should look good.

**Comment by RikaShah** [comment]
i would like to work on this

**Comment by RikaShah** [comment]
using html,css, js and react

**Comment by Vishal1541** [comment]
@RikaShah what's the update?

**Comment by Vishal1541** [comment]
@RikaShah what's the update?

**Comment by RikaShah** [comment]
I have designed and coded the web-page in react, now I have to validate it with database api, and connect it with the homepage
