### ISSUE TITLE
Add snackbar to the top.

### ISSUE THREAD

**Issue by aashish-ak** [KamandPrompt/CodeManiacs#84]
Add a snackbar like the one shown below, to show success/failure notifications on login/signup/form submission etc.

**Comment by Vishal1541** [comment]
Currently, an alert message is being shown on Signing Up. Needs similar thing while Signing In also.

**Comment by kartik1000** [comment]
@Vishal1541 or @aashish-ak Sir can I take up this issue?

**Comment by Vishal1541** [comment]
@kartik1000 Good luck :+1:
